apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-registrations-deployment
spec:
  selector:
    matchLabels:
      app: api-registrations
  template:
    metadata:
      labels:
        app: api-registrations
    spec:
      containers:
        - name: api-registrations-deployment
          image: devrsilva/registrations-microservice
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/v1/livenessProbe
              port: 3004
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 2
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/v1/readinessProbe
              port: 3004
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 2
            timeoutSeconds: 10
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: database-url
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: postgres-host
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: postgres-db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: postgres-password
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-registrations-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 20
---
apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
stringData:
  postgres-db: registrations
  postgres-user: postgres
  postgres-password: postgres
  postgres-host: registration.czg2ea2yu0rz.us-east-1.rds.amazonaws.com
  # database-url: postgresql://postgres:postgres@database-svc/tech_challenge?schema=public
  # postgres-host: dbpostgres.czg2ea2yu0rz.us-east-1.rds.amazonaws.com
  database-url: postgresql://postgres:postgres@registration.czg2ea2yu0rz.us-east-1.rds.amazonaws.com:5432/registrations?schema=public
---
apiVersion: v1
kind: Service
metadata:
  name: api-registrations-svc
spec:
  selector:
    app: api-registrations
  ports:
    - protocol: TCP
      port: 3004
      targetPort: 3004
      nodePort: 30004
  type: LoadBalancer
